version: '2'
services:
  ServiceCenter:
    image: servicecomb/service-center
    ports:
      - 30100:30100
  worker1:
    image: tensorflow/tensorflow
    ports:
      - 8889:8888
  worker1Mesher:
    image: gochassis/mesher
    environment:
      - CSE_REGISTRY_ADDR=http://ServiceCenter:30100
      - SERVICE_NAME=worker1
    network_mode: "service:worker1"
    links:
      - ServiceCenter
      - MyZipkin
  worker2:
    image: tensorflow/tensorflow
    ports:
      - 8890:8888
  worker2Mesher:
    image: gochassis/mesher
    environment:
      - CSE_REGISTRY_ADDR=http://ServiceCenter:30100
      - SERVICE_NAME=worker2
    network_mode: "service:worker1"
    links:
      - ServiceCenter
      - MyZipkin
  MesherConsumer:
    image: gochassis/mesher
    environment:
      - CSE_REGISTRY_ADDR=http://ServiceCenter:30100 #https://cse.cn-north-1.myhwclouds.com:443
      - SERVICE_NAME=Client
      - VERSION=0.0.1
      - APP_ID=default
      - CSE_MONITOR_SERVER_ADDR=
    links:
      - ServiceCenter
      - MyZipkin
    ports:
      - 9000:3000
  Server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:latest

  Client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    environment:
      - http_proxy=127.0.0.1:30101
    network_mode: "service:MesherConsumer"
  MyZipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  Importer:
    image: giantswarm/tiny-tools
    depends_on:
      - MyGrafana
    links:
      - MyGrafana
    entrypoint: /bin/sh import.sh
    working_dir: /opt/grafana-import-dashboards
    volumes:
      - ./grafana:/opt/grafana-import-dashboards
